export const UPDATE_FORM_ONE = 'UPDATE_FORM_ONE';
export const UPDATE_FORM_TWO = 'UPDATE_FORM_TWO';
export const UPDATE_FORM_THREE = 'UPDATE_FORM_THREE';

export const INCREMENT_FORM_INDEX = 'INCREMENT_FORM_INDEX';
export const DECREMENT_FORM_INDEX = 'DECREMENT_FORM_INDEX';
export const FINISH_FORM = 'FINISH_FORM';